baseURL = 'https://jyu1999.com/'
languageCode = 'zh-tw'
title = "Me are 結語JYu"
theme = 'hugo-theme-stack'

googleAnalytics = "G-Y2E5HHC8CW"

enableRobotsTXT = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.7


[module.hugoVersion]
extended = true
min = "0.87.0"


[menu]
[[menu.social]]
identifier = "github"
name = "github"
url = "https://github.com/JYu1999"
weight = -30
[menu.social.params]
icon = "brand-github"
newTab = true
[[menu.social]]
identifier = "linkedin"
name = "linkedin"
url = "https://www.linkedin.com/in/chieh-yu-chan-123814190/"
weight = -20
[menu.social.params]
icon = "brand-linkedin"
newTab = true
[[menu.social]]
identifier = "cv"
name = "cv"
url = "https://jyu1999.notion.site/CHIEH-YU-CHAN-49db0f414780421aae1fb2288114586c"
weight = -10
[menu.social.params]
icon = "file-text"
newTab = true
[[menu.social]]
identifier = "email"
name = "email"
url = "mailto:jk29666338@gmail.com"
weight = -5
[menu.social.params]
icon = "mail"
newTab = false


[params]
mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true
description = "Hi, 我是 結語JYu。我目前是一位後端工程師，同時也是好想工作室後端的小 mentor。在這個網站，我會分享各種科技新知、軟體工程、以及其他我學習到的技術。Hi, I am JYu. I am currently a backend developer. At the same time, I am associate mentor at GoodIdea Studio Backend Camp. In this site, I will share everything I learn, including system design, software engineer or other related to computer science."
image = "image"
favicon = "/favicon.ico"


[params.footer]
since = 2023
customText = "小猴子愛吃香蕉～"

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
compact = false
subtitle_1 = "Backend Developer @ Amastek"
subtitle_2 = "Associate Mentor @ GoodIdea Studio Backend Camp"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"
[params.article]
math = false
toc = true
readingTime = false

[params.article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

[[params.widgets.homepage]]
type = "search"

#[[params.widgets.homepage]]
#type = "archives"
#
#  [params.widgets.homepage.params]
#  limit = 5

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

[[params.widgets.page]]
type = "search"

#[[params.widgets.page]]
#type = "archives"
#
#[params.widgets.page.params]
#limit = 5

[[params.widgets.page]]
type = "categories"

[params.widgets.page.params]
limit = 10

[[params.widgets.page]]
type = "tag-cloud"

[params.widgets.page.params]
limit = 10


[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = true
local = false
src = "img/avatar.png"

[params.colorScheme]
toggle = false
default = "dark"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true
