baseURL = 'https://jyu1999.com/'
languageCode = 'zh-tw'
title = "Me are çµèªJYu"
theme = 'hugo-theme-stack'

[module.hugoVersion]
extended = true
min = "0.87.0"


[menu]
[[menu.social]]
identifier = "github"
name = "github"
url = "https://github.com/JYu1999"
weight = -30
[menu.social.params]
icon = "brand-github"
newTab = true
[[menu.social]]
identifier = "linkedin"
name = "linkedin"
url = "https://www.linkedin.com/in/chieh-yu-chan-123814190/"
weight = -20
[menu.social.params]
icon = ""
newTab = true
[[menu.social]]
identifier = "cv"
name = "cv"
url = "#"
weight = -10
[menu.social.params]
icon = ""
newTab = true
[[menu.social]]
identifier = "email"
name = "email"
url = "jk29666338@gmail.com"
weight = -5
[menu.social.params]
icon = ""
newTab = false


[params]
mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true
description = "Hi, æˆ‘æ˜¯ çµèªJYuã€‚\n åœ¨é€™è£¡æˆ‘æœƒåˆ†äº«ä¸€äº›æˆ‘çš„æƒ³æ³•å’Œæ‰€å­¸ï½"
image = "image"
favicon = "/favicon.ico"

[params.footer]
since = 2023
customText = "å°çŒ´å­æ„›åƒé¦™è•‰ï½"

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
compact = false
emoji = "ğŸ« "
subtitle = "é€™è£¡é è¨ˆæœƒæ”¾è‡ªæˆ‘ä»‹ç´¹ã€‚"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[params.article]
math = false
toc = true
readingTime = true

[params.article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

[[params.widgets.homepage]]
type = "search"

#[[params.widgets.homepage]]
#type = "archives"
#
#  [params.widgets.homepage.params]
#  limit = 5

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

[[params.widgets.page]]
type = "search"

#[[params.widgets.page]]
#type = "archives"
#
#[params.widgets.page.params]
#limit = 5

[[params.widgets.page]]
type = "categories"

[params.widgets.page.params]
limit = 10

[[params.widgets.page]]
type = "tag-cloud"

[params.widgets.page.params]
limit = 10


[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false
src = "img/avatar.png"

[params.colorScheme]
toggle = false
default = "dark"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true
